// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_CKPBkyAWiwOPF2ZA6x8eND2JK_z-JY',
    appId: '1:166195159460:web:70fcec8d2a7132c0dd2131',
    messagingSenderId: '166195159460',
    projectId: 'cotacao-ponto-certo',
    authDomain: 'cotacao-ponto-certo.firebaseapp.com',
    storageBucket: 'cotacao-ponto-certo.appspot.com',
    measurementId: 'G-MRVXPZ571K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5YoEF7hUJxtgwJZaE_VeN9Gry6eiWku8',
    appId: '1:166195159460:android:91b7c7b70edaf26cdd2131',
    messagingSenderId: '166195159460',
    projectId: 'cotacao-ponto-certo',
    storageBucket: 'cotacao-ponto-certo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kWZ6MQXe7hp7lSkB7wuKqMYRvbyhkE8',
    appId: '1:166195159460:ios:39758c2348188331dd2131',
    messagingSenderId: '166195159460',
    projectId: 'cotacao-ponto-certo',
    storageBucket: 'cotacao-ponto-certo.appspot.com',
    iosBundleId: 'com.example.cotacaoPontoCerto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kWZ6MQXe7hp7lSkB7wuKqMYRvbyhkE8',
    appId: '1:166195159460:ios:39758c2348188331dd2131',
    messagingSenderId: '166195159460',
    projectId: 'cotacao-ponto-certo',
    storageBucket: 'cotacao-ponto-certo.appspot.com',
    iosBundleId: 'com.example.cotacaoPontoCerto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh_CKPBkyAWiwOPF2ZA6x8eND2JK_z-JY',
    appId: '1:166195159460:web:6aef4790d1dc24a3dd2131',
    messagingSenderId: '166195159460',
    projectId: 'cotacao-ponto-certo',
    authDomain: 'cotacao-ponto-certo.firebaseapp.com',
    storageBucket: 'cotacao-ponto-certo.appspot.com',
    measurementId: 'G-R5J2RX6C1S',
  );
}
